export const ACTIONS = {
    ADD_NEW_CHAT: 'ADD_NEW_CHAT',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    UPDATE_MESSAGES: 'UPDATE_MESSAGES',
    CLEAR_MESSAGE_TEXT: 'CLEAR_MESSAGE_TEXT',
    CHANGE_MESSAGE_TEXT: 'CHANGE_MESSAGE_TEXT',
    UPDATE_CURRENT_CHAT_ID: 'UPDATE_CURRENT_CHAT_ID'
}